# Generated by Django 5.2.9 on 2026-01-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='TestUser', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
