# Generated by Django 5.2.10 on 2026-01-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
